"""Add tickets, referral, and gamification

Revision ID: c92625823728
Revises: w9s4e5a8f6j2
Create Date: 2026-04-26 10:42:43.240877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92625823728'
down_revision = 'w9s4e5a8f6j2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_plex_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('media_title', sa.String(), nullable=True),
    sa.Column('issue_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_plex_id'], ['user_profiles.plex_user_id'], name=op.f('fk_tickets_user_plex_id_user_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets'))
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_user_plex_id'), ['user_plex_id'], unique=False)

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_plex_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_invitations_owner_plex_id'), ['owner_plex_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_invitations_owner_plex_id_user_profiles'), 'user_profiles', ['owner_plex_id'], ['plex_user_id'])

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('referred_by', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_profiles_referred_by'), ['referred_by'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_user_profiles_payment_token'), ['payment_token'])
        batch_op.create_foreign_key(batch_op.f('fk_user_profiles_referred_by_user_profiles'), 'user_profiles', ['referred_by'], ['plex_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_profiles_referred_by_user_profiles'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_user_profiles_payment_token'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_profiles_referred_by'))
        batch_op.drop_column('referred_by')
        batch_op.drop_column('level')
        batch_op.drop_column('xp')

    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_invitations_owner_plex_id_user_profiles'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invitations_owner_plex_id'))
        batch_op.drop_column('owner_plex_id')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_user_plex_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_status'))

    op.drop_table('tickets')
    # ### end Alembic commands ###
