"""Add block_reason to blocked_users table

Revision ID: 2b5c8a9d1e3f
Revises: 1a2b3c4d5e6f
Create Date: 2025-07-09 12:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5c8a9d1e3f'
down_revision = '1a2b3c4d5e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocked_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('block_reason', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocked_users', schema=None) as batch_op:
        batch_op.drop_column('block_reason')
    # ### end Alembic commands ###
