"""Add libraries to user_profiles table

Revision ID: 3c6d9b0e4f5a
Revises: 2b5c8a9d1e3f
Create Date: 2025-07-14 16:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c6d9b0e4f5a'
down_revision = '2b5c8a9d1e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('libraries', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('libraries')
    # ### end Alembic commands ###
