"""Initial migration.

Revision ID: 89d2378a6ab1
Revises: 
Create Date: 2025-06-27 15:36:04.828568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89d2378a6ab1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('blocked_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('invitations',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('libraries', sa.String(), nullable=False),
    sa.Column('screen_limit', sa.Integer(), nullable=False),
    sa.Column('allow_downloads', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=True),
    sa.Column('claimed_by', sa.String(), nullable=True),
    sa.Column('claimed_at', sa.String(), nullable=True),
    sa.Column('trial_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('overseerr_access', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('limited_users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('screen_limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('pix_payments',
    sa.Column('txid', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('txid')
    )
    op.create_table('user_profiles',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('telegram_user', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('expiration_date', sa.String(), nullable=True),
    sa.Column('last_notification_sent', sa.String(), nullable=True),
    sa.Column('trial_end_date', sa.String(), nullable=True),
    sa.Column('trial_job_id', sa.String(), nullable=True),
    sa.Column('overseerr_access', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_table('pix_payments')
    op.drop_table('limited_users')
    op.drop_table('invitations')
    op.drop_table('blocked_users')
    # ### end Alembic commands ###
