"""Adiciona a tabela de links curtos

Revision ID: 8b5a4c3d2e1f
Revises: 7a9b8c6d5e4f
Create Date: 2025-07-23 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b5a4c3d2e1f'
down_revision = '7a9b8c6d5e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_code', sa.String(length=10), nullable=False),
    sa.Column('original_url', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('short_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_short_links_short_code'), ['short_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('short_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_short_links_short_code'))

    op.drop_table('short_links')
    # ### end Alembic commands ###
