"""Adds unlocked_achievements table for gamification

Revision ID: 9c8d7b6a5e4f
Revises: 8b5a4c3d2e1f
Create Date: 2025-07-28 12:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8d7b6a5e4f'
down_revision = '8b5a4c3d2e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unlocked_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('achievement_id', sa.String(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['user_profiles.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'achievement_id', name='_username_achievement_uc')
    )
    with op.batch_alter_table('unlocked_achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unlocked_achievements_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unlocked_achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unlocked_achievements_username'))

    op.drop_table('unlocked_achievements')
    # ### end Alembic commands ###
