"""Add username to notifications table

Revision ID: a3b4c5d6e7f8
Revises: 9c8d7b6a5e4f
Create Date: 2025-07-28 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b4c5d6e7f8'
down_revision = '9c8d7b6a5e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_notifications_username'), ['username'], unique=False)
        batch_op.create_foreign_key('fk_notifications_username', 'user_profiles', ['username'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notifications_username', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_notifications_username'))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
