"""Adiciona a tabela de rastreio de uso de cupões por utilizador

Revision ID: c3d4e5f6a7b8
Revises: b1c2d3e4f5a6
Create Date: 2025-08-10 14:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d4e5f6a7b8'
down_revision = 'b1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_username', sa.String(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['user_username'], ['user_profiles.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_username', 'coupon_id', name='_user_coupon_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coupon_usages')
    # ### end Alembic commands ###
