"""Add screens to pix_payments table

Revision ID: d3a4b5c6d7e8
Revises: 89d2378a6ab1
Create Date: 2025-06-28 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a4b5c6d7e8'
down_revision = '89d2378a6ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pix_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('screens', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pix_payments', schema=None) as batch_op:
        batch_op.drop_column('screens')
    # ### end Alembic commands ###

