"""Adiciona a tabela de log de términos de stream

Revision ID: e5f6a7b8c9d0
Revises: d4e5f6a7b8c9
Create Date: 2025-09-15 18:05:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f6a7b8c9d0'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream_termination_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('media_title', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stream_termination_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stream_termination_logs_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream_termination_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stream_termination_logs_username'))

    op.drop_table('stream_termination_logs')
    # ### end Alembic commands ###
