"""Add external_reference to pix_payments

Revision ID: f8e7d6c5b4a3
Revises: e1c2a3b4d5f6
Create Date: 2025-06-30 17:55:13.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e7d6c5b4a3'
down_revision = 'e1c2a3b4d5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pix_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_reference', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_pix_payments_external_reference', ['external_reference'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pix_payments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_pix_payments_external_reference', type_='unique')
        batch_op.drop_column('external_reference')

    # ### end Alembic commands ###