"""Add privacy flag to user profiles

Revision ID: c5e4d3b2a1f0
Revises: f8e7d6c5b4a3
Create Date: 2025-07-01 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5e4d3b2a1f0'
down_revision = 'f8e7d6c5b4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hide_from_leaderboard', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('hide_from_leaderboard')
    # ### end Alembic commands ###
